"""adding chat to users model

Revision ID: 1880b42ee868
Revises: 1fc1580541ef
Create Date: 2026-01-26 14:09:14.236835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1880b42ee868'
down_revision: Union[str, Sequence[str], None] = '1fc1580541ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('chat_id', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'chat_id')
    # ### end Alembic commands ###
