"""adding is_actve for OTP

Revision ID: 82eb32bb90d3
Revises: 1880b42ee868
Create Date: 2026-01-28 14:31:35.587595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82eb32bb90d3'
down_revision: Union[str, Sequence[str], None] = '1880b42ee868'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otps', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('otps', 'is_active')
    # ### end Alembic commands ###
